[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "emilek-stonks-peepogamba"
version = "0.1.0"
dependencies = [
  "requests",
  "yfinance",
  "protobuf",
  "curl-cffi",
  "websockets",
]

[project.scripts]
emilek-stonks-peepogamba = "emilek_stonks_peepogamba:main"
